name: Despliegue de API a Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  desplegar-imagen:
    uses: Ciclo-vida-S-II/AUY1104-SharedWorkflows/.github/workflows/deploy-api.yaml@main
    with:
      image-name: "ciclovida-api-edu"
      image-tag: "v1.0.0"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
